// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-properties.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_properties_default = defineTool({
  name: "list_properties",
  title: "List properties",
  description: "List Qit Concierge properties (managed short-term rentals in Dr\xF4me-Ard\xE8che). Returns active listings visible on the public site.",
  inputSchema: {
    active_only: z.boolean().optional().describe("If true, only return active listings. Defaults to true."),
    limit: z.number().int().min(1).max(100).optional().describe("Max number of rows to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ active_only = true, limit = 50 }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("properties").select("id,title,location,description,bedrooms,bathrooms,guests,airbnb_url,booking_url,other_platform_url,other_platform_name,airbnb_rating,is_active").order("created_at", { ascending: false }).limit(limit);
    if (active_only) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { properties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-estimation-request.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_estimation_request_default = defineTool2({
  name: "create_estimation_request",
  title: "Create estimation request",
  description: "Create a new free-estimation lead for Qit Concierge (owner asking for a revenue estimation of their short-term rental).",
  inputSchema: {
    name: z2.string().min(1).max(120),
    email: z2.string().email(),
    phone: z2.string().min(3).max(40),
    city: z2.string().max(120).optional(),
    property_type: z2.string().max(60).optional(),
    beds: z2.string().max(20).optional(),
    surface: z2.string().max(20).optional(),
    platform: z2.string().max(60).optional(),
    online_status: z2.string().max(60).optional(),
    listing_url: z2.string().url().max(500).optional(),
    goal: z2.string().max(500).optional(),
    message: z2.string().max(2e3).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("estimation_requests").insert({ ...input, source: "mcp" }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Estimation request created: ${data.id}` }],
      structuredContent: { request: data }
    };
  }
});

// src/lib/mcp/tools/list-estimation-requests.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_estimation_requests_default = defineTool3({
  name: "list_estimation_requests",
  title: "List estimation requests",
  description: "List incoming free-estimation leads. Admin only \u2014 RLS returns rows only for signed-in admin users.",
  inputSchema: {
    status: z3.string().max(40).optional().describe("Filter by status (e.g. 'new', 'contacted')."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit = 50 }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser3(ctx).from("estimation_requests").select("*").order("created_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { requests: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kwkvzmsnmjoqjllfjoew";
var mcp_default = defineMcp({
  name: "qit-concierge-mcp",
  title: "Qit Concierge",
  version: "0.1.0",
  instructions: "Tools for Qit Concierge, a short-term rental concierge in Dr\xF4me-Ard\xE8che. Use `list_properties` to browse managed listings, `create_estimation_request` to submit a new owner lead, and `list_estimation_requests` (admins only) to review incoming leads.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_properties_default, create_estimation_request_default, list_estimation_requests_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
